# Generated by Django 3.2 on 2022-12-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование курса')),
                ('date_started', models.DateField(verbose_name='Дата начала курсов')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Язык програмирования')),
                ('month_to_learn', models.IntegerField(verbose_name='количество месяцев, продолжительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('work_study_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='место учебы/работы')),
                ('has_own_notebook', models.BooleanField(default=True, verbose_name='Есть ли ноутбук')),
                ('preferred_os', models.CharField(choices=[('windows', 'Windows'), ('mac', 'MacOs'), ('linux', 'Linux')], max_length=10)),
            ],
            options={
                'abstract': False,
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('main_work', models.CharField(blank=True, max_length=50, null=True, verbose_name='основное место работы')),
                ('experience', models.DateField(verbose_name='Опыт работы с:')),
                ('study', models.ManyToManyField(related_name='lessons', through='user.Course', to='user.Student')),
            ],
            options={
                'abstract': False,
                'unique_together': {('email',)},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mentor'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
